### ISSUE TITLE
How to generate IDL straight from given program id?

### ISSUE THREAD

**Issue by OlegJakushkin** [acheroncrypto/native-to-anchor#2]
So all I want is simple - I have a published program to which I have id online and which program I can download with something like `solana program dump 9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin out.ebpf`

So having that id and app file how to try to extract IDL (using this codebase) - could you please share an example?

**Comment by acheroncrypto** [comment]
This is not really about this repo but you can do this with `anchor-cli`:

```sh
anchor idl fetch <ADDRESS> -o idl.json
```

The IDL would need to be deployed on-chain otherwise it wouldn't work.

**Comment by OlegJakushkin** [comment]
Yeah - my hope was it could be done somehow from the binary format in the absence of an anchor file. Thank you.
